# L5: Information extraction

Information extraction (IE) is the task of identifying named entities and semantic relations between these entities in text data. In this lab we will focus on two sub-tasks in IE, **named entity recognition** (identifying mentions of entities) and **entity linking** (matching these mentions to entities in a knowledge base).

We start by loading spaCy:

In [60]:
import spacy

nlp = spacy.load("en_core_web_sm")

The data that we will be using has been tokenized following the conventions of the [Penn Treebank](ftp://ftp.cis.upenn.edu/pub/treebank/public_html/tokenization.html), and we need to prevent spaCy from using its own tokenizer on top of this. We therefore override spaCy&rsquo;s tokenizer with one that simply splits on space.

In [61]:
from spacy.tokens import Doc

class WhitespaceTokenizer(object):
    def __init__(self, vocab):
        self.vocab = vocab

    def __call__(self, text):
        return Doc(self.vocab, words=text.split(" "))

nlp.tokenizer = WhitespaceTokenizer(nlp.vocab)

## Data set

The main data set for this lab is a collection of news wire articles in which mentions of named entities have been annotated with page names from the [English Wikipedia](https://en.wikipedia.org/wiki/). The next code cell loads the training and the development parts of the data into Pandas data frames.

In [150]:
import bz2
import csv
import pandas as pd

with bz2.open("ner-train.tsv.bz2", 'rt',encoding="utf8") as source:
    df_train = pd.read_csv(source, sep='\t', quoting=csv.QUOTE_NONE)

with bz2.open("ner-dev.tsv.bz2", 'rt',encoding="utf8") as source:
    df_dev = pd.read_csv(source, sep='\t', quoting=csv.QUOTE_NONE)

Each row in these two data frames corresponds to one mention of a named entity and has five columns:

1. a unique identifier for the sentence containing the entity mention
2. the pre-tokenized sentence, with tokens separated by spaces
3. the start position of the token span containing the entity mention
4. the end position of the token span (exclusive, as in Python list indexing)
5. the entity label; either a Wikipedia page name or the generic label `--NME--`

The following cell prints the first five samples from the training data:

In [151]:
df_dev.head()

,sentence_id,sentence,beg,end,label
0,0946-000,CRICKET - LEICESTERSHIRE TAKE OVER AT TOP AFTE...,2,3,Leicestershire_County_Cricket_Club
1,0946-001,LONDON 1996-08-30,0,1,London
2,0946-002,West Indian all-rounder Phil Simmons took four...,0,2,West_Indies_cricket_team
3,0946-002,West Indian all-rounder Phil Simmons took four...,3,5,Phil_Simmons
4,0946-002,West Indian all-rounder Phil Simmons took four...,12,13,Leicestershire_County_Cricket_Club

In this sample, we see that the first sentence is annotated with three entity mentions:

* the span 0–1 &lsquo;EU&rsquo; is annotated as a mention but only labelled with the generic `--NME--`
* the span 2–3 &lsquo;German&rsquo; is annotated with the page [Germany](http://en.wikipedia.org/wiki/Germany)
* the span 6–7 &lsquo;British&rsquo; is annotated with the page [United_Kingdom](http://en.wikipedia.org/wiki/United_Kingdom)

## Problem 1: Evaluation measures

To warm up, we ask you to write code to print the three measures that you will be using for evaluation:

In [63]:
def evaluation_report(gold, pred):
    """Print precision, recall, and F1 score.
    
    Args:
        gold: The set with the gold-standard values.
        pred: The set with the predicted values.
    
    Returns:
        Nothing, but prints the precision, recall, and F1 values computed
        based on the specified sets.
    """
    intersection = list(gold & pred)
    
    precision = len(intersection)/len(pred)
    recall = len(intersection)/len(gold)
    F1 = 2*(precision*recall)/(precision+recall)
    
    return (precision,recall,F1)

To test your code, you can run the following cell:

In [64]:

evaluation_report(set(range(3)), set(range(5)))

(0.6, 1.0, 0.7499999999999999)

This should give you a precision of 60%, a recall of 100%, and an F1-value of 75%.

## Problem 2: Span recognition

One of the first tasks that an information extraction system has to solve is to locate and classify (mentions of) named entities, such as persons and organizations. Here we will tackle the simpler task of recognizing **spans** of tokens that contain an entity mention, without the actual entity label.

The English language model in spaCy features a full-fledged [named entity recognizer](https://spacy.io/usage/linguistic-features#named-entities) that identifies a variety of entities, and can be updated with new entity types by the user. Your task in this problem is to evaluate the performance of this component when predicting entity spans in the development data.

Start by implementing a generator function that yields the gold-standard spans in a given data frame.

**Hint:** The Pandas method [`itertuples()`](https://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.itertuples.html) is useful when iterating over the rows in a DataFrame.

In [65]:
def gold_spans(df):
    """Yield the gold-standard mention spans in a data frame.

    Args:
        df: A data frame.

    Yields:
        The gold-standard mention spans in the specified data frame as
        triples consisting of the sentence id, start position, and end
        position of each span.
    """
    df = df_dev.iloc[:,[0,2,3]]

    for rows in df.itertuples(index=False, name=None):
        yield rows

In [66]:
generator = list(gold_spans(df_dev))

In [67]:
print("The first triple is",generator[0],"\nThe last triple is",generator[-1])

The first triple is ('0946-000', 2, 3)
The last triple is ('1161-010', 1, 3)

To test your code, you can count the spans yielded by your function. When called on the development data, you should get a total of 5,917 unique triples. The first triple and the last triple should be

    ('0946-000', 2, 3)
    ('1161-010', 1, 3)

In [68]:
spans_dev_gold = set(gold_spans(df_dev))
print(len(spans_dev_gold))

5917

In [69]:
generator = gold_spans(df_dev)

In [12]:
#next(generator) == [(ent.start_char, ent.end_char, ent.label_) for ent in doc.ents][0]#

NameError: name 'doc' is not defined

Your next task is to write code that calls spaCy to predict the named entities in the development data, and to evaluate the accuracy of these predictions in terms of precision, recall, and F1. Print these scores using the function that you wrote for Problem&nbsp;1.

In [158]:
df  = df_dev.iloc[0:10,:]
df

,sentence_id,sentence,beg,end,label
0,0946-000,CRICKET - LEICESTERSHIRE TAKE OVER AT TOP AFTE...,2,3,Leicestershire_County_Cricket_Club
1,0946-001,LONDON 1996-08-30,0,1,London
2,0946-002,West Indian all-rounder Phil Simmons took four...,0,2,West_Indies_cricket_team
3,0946-002,West Indian all-rounder Phil Simmons took four...,3,5,Phil_Simmons
4,0946-002,West Indian all-rounder Phil Simmons took four...,12,13,Leicestershire_County_Cricket_Club
5,0946-002,West Indian all-rounder Phil Simmons took four...,14,15,Somerset_County_Cricket_Club
6,0946-003,"Their stay on top , though , may be short-live...",13,14,Essex_County_Cricket_Club
7,0946-003,"Their stay on top , though , may be short-live...",15,16,Derbyshire_County_Cricket_Club
8,0946-003,"Their stay on top , though , may be short-live...",17,18,Surrey_County_Cricket_Club
9,0946-003,"Their stay on top , though , may be short-live...",24,25,Kent_County_Cricket_Club

In [76]:
a = df.iloc[:,0]
b = df.iloc[:,0]

In [143]:
res = []
ids = []
for row in df_dev.itertuples(index=False):
    
    if(row[0] in ids):
        continue

    doc = nlp(row[1])
    
    for ent in doc.ents:
        
         res.append((row[0],ent.start, ent.end))
    
    ids.append(row[0])

AttributeError: 'list' object has no attribute 'split'

In [85]:
evaluation_report(set( gold_spans(df_dev)),set(res))

(0.5153023140084598, 0.7000169004563124, 0.5936223575779291)

## Problem 3: Error analysis

As you were able to see in Problem&nbsp;2, the span accuracy of the named entity recognizer is far from perfect. In particular, only slightly more than half of the predicted spans are correct according to the gold standard. Your next task is to analyse this result in more detail.

Write code that prints the false positives and the false negatives from the automatic prediction. Have a look at the output. What are your observations? How could you improve the result? Discuss these questions in a short text.

*TODO: Write a short text that discusses the errors that you observed*

Now, use the insights from your error analysis to improve the automated prediction that you implemented in Problem&nbsp;2. While the best way to do this would be to [update spaCy&rsquo;s NER model](https://spacy.io/usage/linguistic-features#updating) using domain-specific training data, for this lab it suffices to write code to pre-process the data and/or post-process the output produced by spaCy. You should be able to improve the F1 score from Problem&nbsp;2 by at last 15 percentage points.

In [145]:
def preprocess(text):
    doc = nlp(text)
    out = [token.lemma_ for token in doc if not token.is_stop and token.lemma_.isalpha()]
    return out

#preprocessing the data
for row in df_dev.itertuples():    
      df_dev.at[row[0],"sentence"] = " ".join(preprocess(row[2]))

In [149]:
df_dev.head()

,sentence_id,sentence,beg,end,label
0,0946-000,CRICKET leicestershire INNINGS victory,2,3,Leicestershire_County_Cricket_Club
1,0946-001,LONDON,0,1,London
2,0946-002,west indian Phil Simmons take Friday Leicester...,0,2,West_Indies_cricket_team
3,0946-002,west indian Phil Simmons take Friday Leicester...,3,5,Phil_Simmons
4,0946-002,west indian Phil Simmons take Friday Leicester...,12,13,Leicestershire_County_Cricket_Club

In [148]:
res = []
ids = []
for row in df_dev.itertuples(index=False):
    
    if(row[0] in ids):
        continue

    doc = nlp(row[1])
    
    for ent in doc.ents:
        
         res.append((row[0],ent.start, ent.end))
    
    ids.append(row[0])

ValueError: [E031] Invalid token: empty string ('') at position 0.

,sentence_id,sentence,beg,end,label
0,0946-000,CRICKET leicestershire INNINGS victory,2,3,Leicestershire_County_Cricket_Club
1,0946-001,LONDON,0,1,London
2,0946-002,west indian Phil Simmons take Friday Leicester...,0,2,West_Indies_cricket_team
3,0946-002,west indian Phil Simmons take Friday Leicester...,3,5,Phil_Simmons
4,0946-002,west indian Phil Simmons take Friday Leicester...,12,13,Leicestershire_County_Cricket_Club

Show that you achieve the performance goal by reporting the evaluation measures that you implemented in Problem&nbsp;1.

Before going on, we ask you to store the outputs of the improved named entity recognizer on the development data in a new data frame. This new frame should have the same layout as the original data frame for the development data that you loaded above, but should contain the predicted start and end positions for each token span. As the `label` of each span, you can use the special value `--NME--`.

In [ ]:
# TODO: Write code here to store the predicted spans in a new data frame

## Problem 4: Entity linking

Now that we have a method for predicting mention spans, we turn to the task of **entity linking**, which amounts to predicting the knowledge base entity that is referenced by a given mention. In our case, for each span we want to predict the Wikipedia page that this mention references.

Start by extending the generator function that you implemented in Problem&nbsp;2 to labelled spans.

In [245]:
def gold_mentions(df):
    """Yield the gold-standard mentions in a data frame.

    Args:
        df: A data frame.

    Yields:
        The gold-standard mention spans in the specified data frame as
        quadruples consisting of the sentence id, start position, end
        position and entity label of each span.
    """
    
    df = df_dev.iloc[:,[0,2,3,4]]

    for rows in df.itertuples(index=False, name=None):
        yield rows

In [246]:
set(gold_mentions(df))

{('1033-013', 17, 18, 'Flavio_Cotti'),
 ('1083-002', 6, 7, 'Russia'),
 ('1003-003', 18, 19, 'Netherlands'),
 ('0966-051', 4, 5, 'United_Kingdom'),
 ('1125-004', 2, 3, 'Republican_Rally_for_Democracy_in_Rwanda'),
 ('1152-004', 50, 52, 'United_States'),
 ('1101-012', 83, 85, 'Enrique_Alfaro'),
 ('1027-001', 0, 2, '--NME--'),
 ('1106-002', 0, 1, 'Belgium_national_football_team'),
 ('1046-003', 21, 23, '--NME--'),
 ('1069-003', 5, 6, 'Hampshire_County_Cricket_Club'),
 ('1090-003', 3, 5, 'Fed_Cup'),
 ('1120-005', 19, 20, 'Jordan'),
 ('0991-011', 8, 9, 'Boris_Yeltsin'),
 ('1038-004', 0, 2, 'Hong_Kong'),
 ('0979-011', 23, 25, 'Labor_Day'),
 ('0966-067', 4, 5, 'United_States'),
 ('1058-036', 1, 2, 'Detroit'),
 ('1066-050', 0, 1, 'Wycombe_Wanderers_F.C.'),
 ('1116-016', 22, 24, 'Boxer_Protocol'),
 ('1141-008', 0, 1, 'Guangzhou'),
 ('1132-004', 7, 8, '--NME--'),
 ('1160-004', 7, 9, 'Julia_Roberts'),
 ('1058-014', 0, 1, 'Cleveland_Indians'),
 ('0966-036', 4, 5, 'Denmark'),
 ('0967-002', 24, 25, 'Germany'),
 ('1031-000', 5, 6, 'China'),
 ('1096-041', 11, 12, '--NME--'),
 ('1078-005', 7, 8, 'Russia'),
 ('1096-038', 0, 2, '--NME--'),
 ('1066-026', 0, 2, 'Sheffield_United_F.C.'),
 ('1037-002', 3, 6, '--NME--'),
 ('0981-005', 0, 3, '--NME--'),
 ('1142-010', 9, 10, 'United_States'),
 ('0995-019', 20, 21, 'Moscow'),
 ('1056-025', 1, 3, 'Oksana_Grishina'),
 ('1101-012', 88, 90, 'Francisco_Palencia'),
 ('1004-007', 5, 7, '--NME--'),
 ('1058-000', 2, 3, '--NME--'),
 ('0957-021', 10, 11, 'United_States'),
 ('1095-004', 0, 2, 'American_League'),
 ('1058-036', 29, 32, 'Kansas_City_Royals'),
 ('1096-006', 22, 23, '--NME--'),
 ('1070-012', 4, 5, 'Canada'),
 ('1036-035', 1, 2, 'Russia'),
 ('1150-003', 6, 8, '--NME--'),
 ('1055-025', 3, 4, 'Robert_Croft'),
 ('0957-018', 9, 11, 'Cédric_Pioline'),
 ('1082-002', 10, 12, '1998_FIFA_World_Cup'),
 ('1044-005', 0, 1, '--NME--'),
 ('0968-004', 17, 18, 'Sarajevo'),
 ('1053-003', 15, 17, 'Ijaz_Ahmed_(cricketer,_born_1968)'),
 ('0993-005', 27, 28, 'Tanjug'),
 ('0981-013', 0, 1, 'Ford_Motor_Company'),
 ('1095-019', 3, 5, 'New_York_Yankees'),
 ('0966-057', 4, 5, 'Belarus'),
 ('0958-024', 3, 4, 'Detroit_Tigers'),
 ('0997-003', 0, 2, '--NME--'),
 ('1058-017', 19, 21, 'Jim_Leyritz'),
 ('1142-002', 7, 8, 'Iraq'),
 ('1056-025', 4, 5, 'Russia'),
 ('1066-078', 0, 1, 'Rochdale_A.F.C.'),
 ('0966-145', 4, 5, 'United_States'),
 ('1099-009', 9, 11, 'Craig_Brown'),
 ('1072-019', 21, 23, 'Walter_Little_(rugby_player)'),
 ('1022-004', 11, 12, '--NME--'),
 ('1089-026', 10, 14, 'NEC_World_Series_of_Golf'),
 ('1132-003', 11, 12, 'Michoacán'),
 ('1159-002', 0, 1, 'Belgium'),
 ('1159-007', 12, 14, 'Marc_Dutroux'),
 ('1006-004', 14, 16, 'United_Nations'),
 ('1054-010', 6, 7, 'Team_Jumbo–Visma'),
 ('1099-008', 14, 16, 'Andreas_Heraf'),
 ('0966-105', 4, 5, 'Germany'),
 ('0962-009', 22, 24, '--NME--'),
 ('1136-006', 0, 3, '--NME--'),
 ('1087-017', 13, 14, 'Australia'),
 ('0949-011', 8, 9, 'Newcastle_United_F.C.'),
 ('1001-006', 1, 3, '--NME--'),
 ('1078-000', 2, 5, '--NME--'),
 ('1034-002', 25, 27, 'El_Al'),
 ('0996-006', 8, 9, 'Yugoslavia'),
 ('0997-000', 7, 8, 'Interfax'),
 ('1099-018', 17, 19, '--NME--'),
 ('1061-000', 3, 4, 'England'),
 ('1072-011', 0, 1, 'Andrew_Mehrtens'),
 ('1130-000', 2, 5, '--NME--'),
 ('0972-013', 3, 4, 'Romesh_Kaluwitharana'),
 ('0956-016', 0, 1, 'Hanwha_Eagles'),
 ('0972-007', 0, 2, '--NME--'),
 ('0965-006', 2, 4, 'Michael_Green_(sprinter)'),
 ('1128-000', 0, 1, 'Poland'),
 ('1004-005', 8, 10, '--NME--'),
 ('1125-001', 0, 1, 'Nairobi'),
 ('1125-006', 28, 29, 'Democratic_Republic_of_the_Congo'),
 ('1089-002', 0, 2, 'Jesper_Parnevik'),
 ('1154-004', 1, 3, 'Le_Matin_(France)'),
 ('1039-009', 0, 2, 'The_Jakarta_Post'),
 ('1045-002', 13, 14, 'State_of_Palestine'),
 ('0965-003', 17, 18, '--NME--'),
 ('0966-126', 4, 5, 'Ukraine'),
 ('1117-003', 29, 30, 'England'),
 ('1112-003', 33, 35, 'Süddeutsche_Zeitung'),
 ('1058-017', 13, 15, 'Mariano_Duncan'),
 ('1148-005', 18, 19, 'Tunisia'),
 ('1051-003', 22, 23, 'Robert_Allenby'),
 ('1119-005', 0, 1, 'United_Nations'),
 ('0969-000', 5, 6, 'OGC_Nice'),
 ('1155-014', 0, 1, 'Germany'),
 ('0947-009', 21, 23, '--NME--'),
 ('1060-015', 1, 3, 'Stephen_Ames'),
 ('1126-004', 21, 22, 'Sarajevo'),
 ('1116-007', 11, 12, 'Roman_Empire'),
 ('0958-042', 0, 1, 'Chicago_White_Sox'),
 ('1060-004', 2, 3, 'United_Kingdom'),
 ('1054-011', 4, 5, 'Italy'),
 ('0951-002', 0, 1, 'Romania_national_under-21_football_team'),
 ('1009-010', 21, 22, 'United_States'),
 ('1041-000', 0, 2, '--NME--'),
 ('1150-006', 2, 3, 'Boston'),
 ('1067-009', 0, 1, 'Airdrieonians_F.C.'),
 ('1030-027', 1, 3, 'United_States_Department_of_Commerce'),
 ('1076-014', 0, 1, 'FK_Partizan'),
 ('1070-014', 4, 5, 'Brazil'),
 ('1081-002', 10, 11, 'Europe'),
 ('1043-002', 6, 8, 'Changi_Prison'),
 ('1106-001', 0, 1, 'Brussels'),
 ('1116-007', 13, 15, 'Charles_VI,_Holy_Roman_Emperor'),
 ('1154-002', 8, 9, 'Algiers'),
 ('0947-009', 2, 3, 'Sussex_County_Cricket_Club'),
 ('0998-001', 2, 3, 'Russia'),
 ('1022-013', 19, 21, 'Labour_Day'),
 ('1044-007', 22, 23, 'Jerusalem'),
 ('1060-003', 4, 6, 'British_Masters'),
 ('1099-017', 0, 1, 'Austria_national_football_team'),
 ('1030-015', 21, 25, 'New_York_Stock_Exchange'),
 ('1072-019', 72, 74, 'Ian_Jones_(rugby_union)'),
 ('0991-008', 21, 22, 'Chechnya'),
 ('1069-004', 10, 12, '--NME--'),
 ('1060-009', 4, 5, 'Italy'),
 ('1130-006', 0, 1, 'Granma_(newspaper)'),
 ('0951-002', 2, 3, 'Lithuania_national_under-21_football_team'),
 ('1099-017', 8, 10, 'Peter_Schöttel'),
 ('1095-018', 0, 1, 'Houston_Astros'),
 ('1014-003', 17, 19, '--NME--'),
 ('1010-020', 6, 7, 'Cincinnati'),
 ('1030-018', 10, 11, 'Dow_Jones_Industrial_Average'),
 ('1042-003', 5, 6, 'Huize_County'),
 ('1052-005', 0, 1, 'Slovakia_national_football_team'),
 ('1116-034', 0, 1, 'Iraq'),
 ('1054-016', 4, 5, 'Denmark'),
 ('1101-007', 28, 29, 'UEFA_European_Championship'),
 ('0960-025', 13, 14, 'Jeff_Tarango'),
 ('1003-003', 21, 22, '--NME--'),
 ('1056-013', 4, 5, 'Lithuania'),
 ('1143-007', 26, 27, 'Lebanon'),
 ('1160-018', 4, 5, 'Michael_Collins_(Irish_leader)'),
 ('0946-015', 2, 3, 'Kent_County_Cricket_Club'),
 ('1045-001', 0, 2, 'United_Nations'),
 ('1097-004', 41, 44, '--NME--'),
 ('1000-016', 15, 16, '--NME--'),
 ('1072-012', 24, 25, '--NME--'),
 ('1077-006', 5, 7, '1998_FIFA_World_Cup'),
 ('1093-004', 2, 4, 'Joe-Max_Moore'),
 ('0990-014', 0, 1, 'Viktor_Chernomyrdin'),
 ('1099-018', 23, 25, 'Stuart_McCall'),
 ('0984-007', 6, 7, '--NME--'),
 ('1120-006', 12, 13, 'London_Stansted_Airport'),
 ('0972-037', 0, 1, '--NME--'),
 ('1155-010', 0, 1, 'Abolhassan_Banisadr'),
 ('0979-002', 22, 23, 'United_States'),
 ('1074-000', 7, 8, '--NME--'),
 ('0955-011', 0, 1, 'Pohang_Steelers'),
 ('0966-161', 16, 17, 'Namibia'),
 ('0986-006', 10, 11, 'Ian_Harte'),
 ('1033-005', 22, 23, 'Switzerland'),
 ('1018-004', 14, 15, 'Berlin'),
 ('1019-000', 6, 7, 'Netherlands'),
 ('1128-003', 19, 21, 'Zygmunt_Solorz-Żak'),
 ('0966-041', 4, 5, 'Russia'),
 ('1053-002', 2, 3, 'Pakistan_national_cricket_team'),
 ('0960-005', 8, 9, 'Marcelo_Ríos'),
 ('0947-006', 7, 9, '--NME--'),
 ('1011-014', 0, 1, 'KeyBank'),
 ('1051-003', 15, 16, 'Spain'),
 ('1111-006', 4, 6, '--NME--'),
 ('1066-018', 0, 2, 'Port_Vale_F.C.'),
 ('1056-034', 27, 29, 'Francis_Moreau'),
 ('1069-017', 4, 5, 'Nottinghamshire_County_Cricket_Club'),
 ('0947-001', 0, 1, 'London'),
 ('0966-100', 1, 3, 'Michael_Green_(sprinter)'),
 ('1064-002', 1, 2, 'Australia_national_rugby_union_team'),
 ('1096-006', 5, 7, 'John_Boles_(baseball)'),
 ('1014-001', 2, 3, 'California'),
 ('1067-008', 7, 9, 'St_Johnstone_F.C.'),
 ('1101-000', 2, 3, 'France_national_football_team'),
 ('0963-011', 0, 1, 'Nolan_Henke'),
 ('0957-033', 9, 11, 'Todd_Martin'),
 ('0958-019', 0, 1, 'Texas_Rangers_(baseball)'),
 ('0957-013', 0, 2, 'Jonas_Björkman'),
 ('1016-009', 0, 1, '--NME--'),
 ('0966-127', 1, 3, 'Alina_Astafei'),
 ('1027-009', 13, 14, 'Jerusalem'),
 ('1103-009', 41, 43, 'Ogün_Temizkanoğlu'),
 ('1033-009', 0, 1, 'Flavio_Cotti'),
 ('1069-006', 1, 2, 'Riverside_Ground'),
 ('1004-002', 3, 5, 'Norodom_Sihanouk'),
 ('1060-016', 1, 3, 'Frank_Nobilo'),
 ('1142-000', 7, 8, 'Iraq'),
 ('1027-011', 12, 13, 'State_of_Palestine'),
 ('1017-011', 2, 3, '--NME--'),
 ('1075-002', 4, 5, 'Benin_national_football_team'),
 ('1155-002', 0, 1, 'Iran'),
 ('1076-028', 0, 1, 'FK_Rudar_Ugljevik'),
 ('0974-010', 3, 5, 'Roshan_Mahanama'),
 ('1099-018', 5, 7, 'Craig_Burley'),
 ('1015-000', 0, 1, 'RMS_Titanic'),
 ('1137-000', 0, 2, 'North_Korea'),
 ('1011-005', 15, 16, '--NME--'),
 ('1066-027', 0, 1, 'Grimsby_Town_F.C.'),
 ('1068-024', 0, 2, 'Notts_County_F.C.'),
 ('1001-003', 20, 21, '--NME--'),
 ('0967-001', 0, 1, 'Geneva'),
 ('1011-004', 26, 31, '--NME--'),
 ('0966-022', 1, 3, 'Tony_Jarrett'),
 ('1014-009', 16, 18, 'Jack_Kemp'),
 ('0962-009', 13, 15, 'Willie_Wood_(golfer)'),
 ('0957-030', 11, 12, 'Madagascar'),
 ('0963-002', 26, 28, 'Tiger_Woods'),
 ('0958-056', 2, 4, '--NME--'),
 ('1069-010', 20, 21, 'Derbyshire_County_Cricket_Club'),
 ('0982-000', 0, 1, '--NME--'),
 ('0963-017', 0, 1, 'Nolan_Henke'),
 ('1048-001', 0, 1, '--NME--'),
 ('1073-002', 20, 22, 'Ellis_Park_Stadium'),
 ('1068-025', 0, 1, 'Shrewsbury_Town_F.C.'),
 ('0966-090', 1, 3, 'Falilat_Ogunkoya'),
 ('0965-003', 1, 3, 'Dennis_Mitchell'),
 ('1089-011', 0, 1, 'Jesper_Parnevik'),
 ('0959-015', 2, 4, '--NME--'),
 ('1117-003', 24, 25, 'Worthing'),
 ('1094-055', 3, 4, 'Montreal_Expos'),
 ('1062-003', 25, 27, 'John_Robinson_(footballer)'),
 ('0966-144', 4, 5, 'Cuba'),
 ('1134-002', 0, 1, 'Philippines'),
 ('1049-003', 18, 20, 'Andy_Townsend'),
 ('1055-018', 6, 8, 'Waqar_Younis'),
 ('1076-005', 0, 1, 'FK_Hajduk_Kula'),
 ('1096-027', 6, 8, 'David_Segui'),
 ('1096-043', 0, 1, 'Donne_Wall'),
 ('1094-045', 0, 2, 'San_Diego_Padres'),
 ('1006-007', 9, 10, 'Ghana'),
 ('1000-015', 41, 42, 'Hungary'),
 ('1030-013', 14, 15, 'Japan'),
 ('1084-000', 4, 5, 'Latvia_national_football_team'),
 ('1058-025', 7, 9, 'Edgar_Martínez'),
 ('1044-002', 2, 4, 'Yasser_Arafat'),
 ('0980-015', 5, 6, 'Federal_Reserve'),
 ('1066-049', 0, 1, 'Luton_Town_F.C.'),
 ('1016-010', 12, 13, 'Bonn'),
 ('1056-034', 16, 17, 'France'),
 ('1056-016', 22, 24, 'Anton_Shantyr'),
 ('0965-011', 31, 32, 'Berlin'),
 ('0998-002', 0, 1, 'Russia'),
 ('1035-010', 34, 35, 'Russia'),
 ('0966-127', 4, 5, 'Germany'),
 ('0972-013', 5, 6, 'Upul_Chandana'),
 ('0986-003', 15, 17, 'Ian_Harte'),
 ('1066-053', 0, 1, 'Rotherham_United_F.C.'),
 ('0949-005', 12, 14, 'Glenn_Hoddle'),
 ('0994-008', 27, 28, 'Reuters'),
 ('1057-003', 11, 12, 'Lancashire_County_Cricket_Club'),
 ('1104-002', 16, 18, '--NME--'),
 ('0966-083', 4, 5, 'United_States'),
 ('1156-002', 18, 19, 'Burundi'),
 ('0964-002', 21, 22, 'FIFA'),
 ('1131-006', 19, 21, 'Latin_America'),
 ('1066-073', 0, 2, 'Leyton_Orient_F.C.'),
 ('1128-002', 26, 28, '--NME--'),
 ('1058-030', 10, 11, 'Chicago_White_Sox'),
 ('1076-007', 2, 6, '--NME--'),
 ('1129-002', 19, 20, 'Interfax'),
 ('0966-131', 1, 3, 'Yelena_Gulyayeva'),
 ('1057-007', 25, 27, 'Saqlain_Mushtaq'),
 ('0957-006', 8, 10, 'Scott_Draper'),
 ('1116-015', 11, 12, 'Naples'),
 ('1144-000', 0, 1, '--NME--'),
 ('0966-030', 1, 3, 'Frankie_Fredericks'),
 ('0985-006', 0, 1, 'Frank_Bruno'),
 ('0974-009', 0, 2, 'Romesh_Kaluwitharana'),
 ('0996-001', 0, 1, 'Warsaw'),
 ('1070-016', 5, 6, 'Brazil'),
 ('0948-025', 3, 4, 'Gloucestershire_County_Cricket_Club'),
 ('1090-002', 0, 2, 'New_York_City'),
 ('0966-162', 10, 11, 'Nigeria'),
 ('0972-006', 0, 2, '--NME--'),
 ('1131-000', 0, 1, 'United_Nations'),
 ('1056-008', 4, 5, 'Australia'),
 ('0976-000', 0, 1, 'Poland'),
 ('1160-002', 2, 3, 'Italy'),
 ('1109-000', 6, 7, 'Brazil_national_football_team'),
 ('0946-002', 3, 5, 'Phil_Simmons'),
 ('1070-014', 1, 3, 'André_Ribeiro'),
 ('1099-005', 13, 15, 'SC_Freiburg'),
 ('1025-006', 0, 1, 'State_of_Palestine'),
 ('1054-010', 4, 5, 'Russia'),
 ('1147-002', 13, 14, 'Iraq'),
 ('0957-008', 6, 8, 'Andrei_Olhovskiy'),
 ('1007-007', 13, 14, 'Bill_Clinton'),
 ('0996-007', 8, 9, 'Yugoslavia'),
 ('1022-013', 10, 11, 'Canada'),
 ('0981-008', 23, 24, '--NME--'),
 ('0957-012', 6, 8, 'Mikael_Tillström'),
 ('1022-002', 0, 1, 'Canada'),
 ('1087-017', 0, 1, 'Jansher_Khan'),
 ('0988-001', 0, 1, 'Johannesburg'),
 ('1139-000', 4, 6, '--NME--'),
 ('1022-007', 5, 6, 'Canada'),
 ('0946-006', 28, 29, 'Headingley'),
 ('1039-001', 19, 20, 'Jakarta'),
 ('1090-008', 32, 35, 'Billie_Jean_King'),
 ('0995-006', 0, 1, '--NME--'),
 ('0947-006', 0, 1, 'Chester-le-Street'),
 ('1016-008', 40, 41, '--NME--'),
 ('0963-023', 0, 2, 'Phil_Mickelson'),
 ('1004-003', 10, 12, '--NME--'),
 ('1072-018', 60, 62, '--NME--'),
 ('1058-029', 0, 1, 'Harold_Baines'),
 ('1035-000', 2, 3, 'Azerbaijan'),
 ('0994-010', 23, 24, 'Russia'),
 ('1031-004', 37, 38, 'Wuxi'),
 ('0956-010', 6, 7, '--NME--'),
 ('1039-014', 11, 14, '--NME--'),
 ('1144-003', 7, 8, 'Iraq'),
 ('1095-008', 2, 3, 'Cleveland_Indians'),
 ('1104-002', 6, 7, 'Spain'),
 ('1152-018', 18, 19, 'United_States'),
 ('1135-026', 0, 2, 'Aung_San_Suu_Kyi'),
 ('1128-011', 8, 9, '--NME--'),
 ('0966-141', 1, 3, 'Fita_Bayisa'),
 ('1116-009', 23, 24, 'Moscow'),
 ('1004-003', 24, 25, '--NME--'),
 ('1068-019', 2, 4, 'Bristol_City_F.C.'),
 ('0949-000', 5, 6, 'England_national_football_team'),
 ('0963-002', 0, 2, 'Nolan_Henke'),
 ('1020-008', 1, 3, '--NME--'),
 ('1103-015', 15, 17, 'Dirk_Medved'),
 ('1057-006', 11, 13, 'Alec_Stewart'),
 ('1056-032', 1, 3, '--NME--'),
 ('1077-000', 2, 3, 'Paul_Ince'),
 ('1143-004', 16, 17, 'Lebanon'),
 ('1116-008', 6, 7, 'France'),
 ('1030-038', 13, 17, 'New_York_Cotton_Exchange'),
 ('1146-005', 48, 49, 'Iran'),
 ('1101-009', 12, 14, '1998_FIFA_World_Cup'),
 ('1054-017', 6, 7, '7-Eleven_(cycling_team)'),
 ('0958-038', 0, 2, 'National_League_Central'),
 ('0966-040', 4, 5, 'Germany'),
 ('1084-002', 10, 11, 'Europe'),
 ('1094-001', 0, 2, 'New_York_City'),
 ('1101-011', 87, 89, 'Zinedine_Zidane'),
 ('0947-008', 22, 24, '--NME--'),
 ('1131-002', 5, 7, 'United_Nations'),
 ('1002-000', 4, 5, 'Colombia'),
 ('1160-003', 34, 37, 'Venice_Film_Festival'),
 ('0984-017', 17, 18, 'United_States'),
 ('0968-000', 8, 9, 'Sarajevo'),
 ('1101-011', 0, 1, 'France_national_football_team'),
 ('1121-008', 3, 4, 'Iraq'),
 ('1032-007', 6, 7, 'Germany'),
 ('1096-025', 24, 27, 'San_Diego_Padres'),
 ('1111-009', 2, 4, 'Richard_Hannon'),
 ('1160-015', 17, 19, 'Kitty_Kiernan'),
 ('1076-002', 2, 3, 'Yugoslavia'),
 ('1088-002', 21, 22, 'Pakistan'),
 ('1060-003', 0, 2, 'PGA_European_Tour'),
 ('1154-002', 16, 17, 'Algeria'),
 ('1037-004', 3, 4, '--NME--'),
 ('1068-031', 2, 3, 'Darlington_F.C.'),
 ('1101-008', 33, 35, '--NME--'),
 ('1142-000', 3, 4, 'Iran'),
 ('0983-007', 12, 13, 'Cyprus'),
 ('0952-003', 17, 18, 'FC_Rotor_Volgograd'),
 ('0957-012', 0, 2, 'Alexander_Volkov_(tennis)'),
 ('1127-006', 8, 9, '--NME--'),
 ('1155-009', 15, 16, 'Berlin'),
 ('1048-003', 0, 1, 'Israel_national_under-21_football_team'),
 ('1027-024', 4, 5, 'Yasser_Arafat'),
 ('0974-000', 2, 3, 'Australia_national_cricket_team'),
 ('1048-003', 3, 4, 'Bulgaria_national_under-21_football_team'),
 ('1056-046', 0, 2, 'Lucy_Tyler-Sharman'),
 ('1110-002', 14, 16, 'James_Heath_(boxer)'),
 ('0966-037', 4, 5, 'Cuba'),
 ('1155-009', 19, 20, 'Iran'),
 ('0985-009', 14, 16, 'Oliver_McCall'),
 ('1038-003', 11, 13, '--NME--'),
 ('1038-007', 8, 10, 'Hong_Kong'),
 ('0986-003', 8, 10, 'Phil_Babb'),
 ('0957-020', 26, 28, 'Paul_Haarhuis'),
 ('1081-002', 0, 1, 'Armenia_national_football_team'),
 ('1055-024', 4, 5, 'Alan_Mullally'),
 ('1132-004', 10, 12, '--NME--'),
 ('1008-028', 0, 1, '--NME--'),
 ('1019-013', 8, 9, 'Netherlands'),
 ('1011-022', 15, 17, '--NME--'),
 ('1096-012', 32, 36, '--NME--'),
 ('1095-019', 0, 2, 'San_Francisco_Giants'),
 ('0988-002', 21, 27, '--NME--'),
 ('1116-006', 7, 8, 'House_of_Orléans'),
 ('1056-026', 1, 3, 'Tanya_Dubnicoff'),
 ('0967-005', 21, 22, 'Karlsruher_SC'),
 ('1108-004', 8, 9, 'Nate_Miller'),
 ('1097-011', 11, 12, '--NME--'),
 ('1116-037', 13, 14, 'Uzbekistan'),
 ('1055-027', 0, 2, 'Saleem_Malik'),
 ('1091-003', 14, 16, 'Natasha_Zvereva'),
 ('1009-018', 27, 29, '--NME--'),
 ('1101-012', 46, 49, 'Joaquín_del_Olmo'),
 ('0997-006', 0, 2, '--NME--'),
 ('0990-014', 22, 23, 'Chechnya'),
 ('0966-141', 4, 5, 'Ethiopia'),
 ('1154-006', 26, 27, 'Algeria'),
 ('1119-006', 0, 1, 'Erbil'),
 ('1096-000', 9, 10, 'Cincinnati_Reds'),
 ('1066-051', 0, 1, 'Wrexham_A.F.C.'),
 ('1133-004', 33, 35, 'Deng_Xiaoping'),
 ('1096-020', 24, 26, 'Tom_Glavine'),
 ('1096-034', 6, 8, 'Álvaro_Espinoza'),
 ('1126-009', 9, 10, 'Serbia'),
 ('1025-009', 18, 19, 'Israel'),
 ('1068-035', 0, 1, 'Mansfield_Town_F.C.'),
 ('0961-001', 0, 1, 'Philadelphia'),
 ('1033-000', 0, 1, '--NME--'),
 ('1044-004', 28, 29, 'Islam'),
 ('1070-012', 1, 3, 'Paul_Tracy'),
 ('0998-003', 0, 1, 'Alexander_Lebed'),
 ('1158-001', 0, 1, 'Brussels'),
 ('1160-004', 28, 29, 'Republic_of_Ireland'),
 ('1051-009', 32, 34, 'Klas_Eriksson'),
 ('1103-016', 64, 66, 'Hakan_Şükür'),
 ('0962-004', 1, 6, 'Brown_Deer_Park_Golf_Course'),
 ('1066-013', 0, 1, 'Swindon_Town_F.C.'),
 ('1076-021', 0, 4, '--NME--'),
 ('1045-004', 32, 33, '--NME--'),
 ('0946-012', 20, 21, 'Derbyshire_County_Cricket_Club'),
 ('1138-003', 2, 3, 'Hangzhou'),
 ('1127-022', 39, 40, 'Chechnya'),
 ('1025-003', 4, 5, 'Israel'),
 ('0966-118', 1, 3, 'Maksim_Tarasov'),
 ('1029-014', 21, 23, 'New_York_Stock_Exchange'),
 ('1155-015', 8, 9, 'Germany'),
 ('1138-003', 13, 14, '--NME--'),
 ('0967-002', 18, 19, 'UEFA_Intertoto_Cup'),
 ('0966-015', 1, 3, 'Yekaterina_Podkopayeva'),
 ('1091-001', 0, 2, 'New_York_City'),
 ('1116-015', 2, 4, 'Giuseppe_Garibaldi'),
 ('1116-033', 8, 9, 'Kuwait'),
 ('1046-004', 26, 27, 'Brazil'),
 ('1058-007', 10, 12, 'Rubén_Sierra'),
 ('1075-002', 7, 10, 'Africa_Cup_of_Nations'),
 ('1072-006', 0, 1, 'South_Africa_national_rugby_union_team'),
 ('1144-001', 0, 1, 'Baghdad'),
 ('1122-002', 18, 19, 'Algeria'),
 ('1054-004', 3, 4, 'Landgraaf'),
 ('1128-014', 15, 16, '--NME--'),
 ('1049-003', 24, 26, '--NME--'),
 ('1096-040', 0, 2, 'Eric_Anthony'),
 ('0946-004', 14, 15, 'Leicestershire_County_Cricket_Club'),
 ('0958-014', 0, 1, 'Chicago_White_Sox'),
 ('0958-018', 0, 2, 'National_League_West'),
 ('1115-003', 26, 27, 'Northern_Ireland'),
 ('1051-010', 32, 34, '--NME--'),
 ('1097-000', 2, 3, 'Stefan_Edberg'),
 ('0960-010', 27, 28, 'MaliVai_Washington'),
 ('0980-003', 3, 4, '--NME--'),
 ('1142-000', 0, 2, 'Iraqi_Kurdistan'),
 ('1069-013', 25, 27, '--NME--'),
 ('0956-004', 0, 1, '--NME--'),
 ('1027-009', 0, 1, 'State_of_Palestine'),
 ('1148-003', 0, 1, 'Reuters'),
 ('0980-000', 8, 9, 'Chicago'),
 ('1069-003', 1, 2, 'Portsmouth'),
 ('1121-007', 27, 28, 'Iraq'),
 ('0991-006', 4, 5, 'Aslan_Maskhadov'),
 ('1017-003', 34, 36, 'Air_France'),
 ('1033-013', 0, 1, 'Chechnya'),
 ('1104-002', 8, 9, '--NME--'),
 ('1101-002', 6, 8, 'Youri_Djorkaeff'),
 ('0963-003', 12, 14, 'Billy_Andrade'),
 ('1057-007', 8, 10, 'Ijaz_Ahmed_(cricketer,_born_1968)'),
 ('1045-007', 21, 22, 'Israel'),
 ('1055-001', 0, 1, 'Birmingham'),
 ('1101-002', 3, 5, 'Nicolas_Ouédec'),
 ('1133-006', 29, 30, 'China'),
 ('1161-000', 0, 1, 'Dhaka_Stock_Exchange'),
 ('0966-034', 4, 5, 'Belgium'),
 ('1030-032', 15, 16, 'Democratic_Party_(United_States)'),
 ('1066-054', 0, 1, 'Walsall_F.C.'),
 ('1069-012', 7, 8, 'Surrey_County_Cricket_Club'),
 ('0989-001', 0, 1, '--NME--'),
 ('1160-010', 0, 1, 'Neil_Jordan'),
 ('1119-001', 0, 1, 'London'),
 ('0972-028', 4, 5, '--NME--'),
 ('1105-004', 3, 5, 'Real_Madrid_CF'),
 ('1103-016', 59, 61, 'Tayfun_Korkut'),
 ('1056-034', 18, 20, '--NME--'),
 ('1032-003', 4, 5, '--NME--'),
 ('1054-008', 1, 3, 'Erik_Breukink'),
 ('0986-002', 3, 5, 'Mick_McCarthy'),
 ('1030-007', 6, 7, '--NME--'),
 ('0994-014', 5, 6, 'Moscow'),
 ('1130-006', 17, 18, 'United_States'),
 ('1137-010', 0, 2, 'South_Korea'),
 ('1101-000', 5, 7, '1998_FIFA_World_Cup'),
 ('0947-007', 10, 12, '--NME--'),
 ('1022-005', 1, 2, 'United_States'),
 ('1116-035', 2, 3, 'United_Kingdom'),
 ('0946-005', 4, 5, 'Somerset_County_Cricket_Club'),
 ('1096-031', 1, 3, 'New_York_City'),
 ('1052-004', 3, 6, '--NME--'),
 ('1005-002', 0, 2, 'Hong_Kong'),
 ('1157-004', 28, 29, 'Iraq'),

A naive baseline for entity linking on our data set is to link each mention span to the Wikipedia page name that we get when we join the tokens in the span by underscores, as is standard in Wikipedia page names. Suppose, for example, that a span contains the two tokens

    Jimi Hendrix

The baseline Wikipedia page name for this span would be

    Jimi_Hendrix

Implement this naive baseline and evaluate its performance. Print the evaluation measures that you implemented in Problem&nbsp;1.

<div class="alert alert-warning">
    Here and in the remainder of this lab, you should base your entity predictions on the predicted spans that you computed in Problem&nbsp;3.
</div>

In [196]:
res = []
ids = []
for row in df_dev.itertuples():
    
    if(row[1] in ids):
        continue

    doc = nlp(row[2])
    
    for ent in doc.ents:
        
         res.append((row[1],ent.start, ent.end,"_".join(df_dev.iloc[row[0],1].split(" ")[df_dev.iloc[row[0],2]:df_dev.iloc[row[0],3]])))
    
    ids.append(row[1])

In [199]:
evaluation_report(set(gold_mentions(df_dev)),set(res))

(0.05934312017914904, 0.08061517660976847, 0.068362594052311)

## Problem 5: Extending the training data using the knowledge base

State-of-the-art approaches to entity linking exploit information in knowledge bases. In our case, where Wikipedia is the knowledge base, one particularly useful type of information are links to other Wikipedia pages. In particular, we can interpret the anchor texts (the highlighted texts that you click on when you click on a link) as mentions of the entities (pages) that they link to. This allows us to harvest long lists over mention–entity pairings.

The following cell loads a data frame summarizing anchor texts and page references harvested from the first paragraphs of the English Wikipedia. The data frame also contains all entity mentions in the training data (but not the development or the test data).

In [243]:
with bz2.open("kb.tsv.bz2", 'rt',encoding="utf8") as source:
    df_kb = pd.read_csv(source, sep='\t', quoting=csv.QUOTE_NONE)

To understand what information is available in this data, the following cell shows the entry for the anchor text `Sweden`.

In [244]:
df_kb.loc[df_kb["mention"] == "Sweden"]

      mention                                 entity      prob
17436  Sweden                                 Sweden  0.985768
17437  Sweden          Sweden_national_football_team  0.014173
17438  Sweden  Sweden_men's_national_ice_hockey_team  0.000059

As you can see, each row of the data frame contains a pair $(m, e)$ of a mention $m$ and an entity $e$, as well as the conditional probability $P(e|m)$ for mention $m$ referring to entity $e$. These probabilities were estimated based on the frequencies of mention–entity pairs in the knowledge base. The example shows that the anchor text &lsquo;Sweden&rsquo; is most often used to refer to the entity [Sweden](http://en.wikipedia.org/wiki/Sweden), but in a few cases also to refer to Sweden&rsquo;s national football and ice hockey teams. Note that references are sorted in decreasing order of probability, so that the most probable pairing stands first.

Implement an entity linking method that resolves each mention to the most probable entity in the data frame. If the mention is not included in the data frame, you can predict the generic label `--NME--`. Print the precision, recall, and F1 of your method using the function that you implemented for Problem&nbsp;1.

In [240]:
mention = [ " ".join(df_train.iloc[row[0],1].split(" ")[df_train.iloc[row[0],2]:df_train.iloc[row[0],3]]) for row in df_train.itertuples()]

In [241]:
res = []
ids = []
for row in df_dev.itertuples(index=False):

    doc = nlp(row[1])
    
    for ent in doc.ents:
        
         res.append((row[0],ent.start, ent.end))
    
    ids.append(row[0])

'EU'

In [242]:
df_dev.head()

,sentence_id,sentence,beg,end,label
0,0946-000,CRICKET - LEICESTERSHIRE TAKE OVER AT TOP AFTE...,2,3,Leicestershire_County_Cricket_Club
1,0946-001,LONDON 1996-08-30,0,1,London
2,0946-002,West Indian all-rounder Phil Simmons took four...,0,2,West_Indies_cricket_team
3,0946-002,West Indian all-rounder Phil Simmons took four...,3,5,Phil_Simmons
4,0946-002,West Indian all-rounder Phil Simmons took four...,12,13,Leicestershire_County_Cricket_Club

In [239]:
#a[0] in df_kb["mention"].values

predictions = 
for m in mention:
    if(m  in df_kb["mention"].values):

True

## Problem 6: Context-sensitive disambiguation

Consider the entity mention &lsquo;Lincoln&rsquo;. The most probable entity for this mention turns out to be [Lincoln, Nebraska](http://en.wikipedia.org/Lincoln,_Nebraska); but in pages about American history, we would be better off to predict [Abraham Lincoln](http://en.wikipedia.org/Abraham_Lincoln). This suggests that we should try to disambiguate between different entity references based on the textual context on the page from which the mention was taken. Your task in this last problem is to implement this idea.

Set up a dictionary that contains, for each mention $m$ that can refer to more than one entity $e$, a separate Naive Bayes classifier to predict the correct entity $e$, given the textual context of the mention. As the prior probabilities of the classifier, choose the probabilities $P(e|m)$ that you used in Problem&nbsp;5. To let you estimate the context-specific probabilities, we have compiled a data set with mention contexts:

In [ ]:
with bz2.open("contexts.tsv.bz2") as source:
    df_contexts = pd.read_csv(source, sep='\t', quoting=csv.QUOTE_NONE)

This data frame contains, for each ambiguous mention $m$ and each knowledge base entity $e$ to which this mention can refer, up to 100 randomly selected contexts in which $m$ is used to refer to $e$. For this data, a **context** is defined as a bag of words containing the mention itself, as well as the 5 tokens to the left and the 5 tokens to the right of the mention. Here are a few examples:

In [ ]:
df_contexts.head()

From this data frame, it is easy to select the data that you need to train the classifiers – the contexts and corresponding entities for all mentions. To illustrate this, the following cell shows how to select all contexts that belong to the mention &lsquo;Lincoln&rsquo;:

In [ ]:
df_contexts.context[df_contexts.mention == "Lincoln"]

Implement the context-sensitive disambiguation method and evaluate its performance. Here are some more hints that may help you along the way:

**Hint 1:** The prior probabilities for a Naive Bayes classifier can be specified using the `class_prior` option. You will have to provide the probabilities in the same order as the alphabetically sorted class (entity) names.

**Hint 2:** To tune the performance of your method, you can try to tweak the behaviour of the vectorizer (for example, should it apply lowercasing or not?) and the width of the window from which you are extracting context tokens at prediction time.

**Hint 3:** Not all mentions in the knowledge base are ambiguous, and therefore not all mentions have context data. If a mention has only one possible entity, pick that one. If a mention has no entity at all, predict the `--NME--` label.

In [ ]:
# TODO: Write code here to implement the context-sensitive disambiguation method

You should expect to see a small (around 1&nbsp;unit) increase in both precision, recall, and F1. Published systems report a larger impact of context-sensitive disambiguation. Feel free to think about what could explain the relatively minor impact that we see here!

**This was the last lab in the Text Mining course. Well done!**

<div class="alert alert-info">
    Please read the section ‘General information’ on the ‘Labs’ page of the course website before submitting this notebook!
</div>